---
title: "Michigan Explore"
author: "Blain Morin"
date: "11/30/2021"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, cache = TRUE)
library(tidyverse)
library(lubridate)
library(readr)
library(plotly)

```

```{r}

### Treatment Data
treatments = read_csv("treatments.csv")


### Assemble 2016 - 2020 data
arr16 = readRDS("~/michigan_arrests/data/ucr_arrests_monthly_all_crimes_race_sex_2016.rds")
arr16 = arr16 %>%
  filter(state_abb == "MI") %>%
  select(fips_county_code, state, agency_name, year, month, starts_with("dui"))


arr17 = readRDS("~/michigan_arrests/data/ucr_arrests_monthly_all_crimes_race_sex_2017.rds")
arr17 = arr17 %>%
  filter(state_abb == "MI") %>%
  select(fips_county_code, state, agency_name, year, month, starts_with("dui"))


arrest = rbind(arr16, arr17)


arr18 = readRDS("~/michigan_arrests/data/ucr_arrests_monthly_all_crimes_race_sex_2018.rds")
arr18 = arr18 %>%
  filter(state_abb == "MI") %>%
  select(fips_county_code, state, agency_name, year, month, starts_with("dui"))


arrest = rbind(arrest, arr18)


arr19 = readRDS("~/michigan_arrests/data/ucr_arrests_monthly_all_crimes_race_sex_2019.rds")
arr19 = arr19 %>%
  filter(state_abb == "MI") %>%
  select(fips_county_code, state, agency_name, year, month, starts_with("dui"))


arrest = rbind(arrest, arr19)


arr20 = readRDS("~/michigan_arrests/data/ucr_arrests_monthly_all_crimes_race_sex_2020.rds")
arr20 = arr20 %>%
  filter(state_abb == "MI") %>%
  select(fips_county_code, state, agency_name, year, month, starts_with("dui"))



arrest = rbind(arrest, arr20)


### Remove to save RAM
remove(arr16, arr17, arr18, arr19, arr20)


### Create Dates
arrest = arrest %>%
  mutate(monthyear = paste(month, year)) %>%
  mutate(d = my(monthyear))





### Attach swab count to respective county and phase
phase1_treated = treatments %>%
  filter(phase == "one") %>%
  select(fips_county_code, number_of_tests)

phase1_ids = phase1_treated$fips_county_code


phase2_treated = treatments %>%
  filter(phase == "two") %>%
  select(fips_county_code, number_of_tests)

phase2_ids = phase2_treated$fips_county_code

treated_ids = unique(treatments$fips_county_code)


phase1_start = my("november 2017")
phase1_end = my("october 2018") # Using October because phase 1 ended on 11/8
phase2_start = my("october 2019")
phase2_end = my("september 2020")


phase1_interval = interval(start = phase1_start, end = phase1_end)
phase2_interval = interval(start = phase2_start, end = phase2_end)


arrest = arrest %>%
  left_join(phase1_treated) %>% 
  mutate(number_of_tests = replace_na(number_of_tests, 0)) %>%
  rename(phase1_swabs = number_of_tests) %>%
  mutate(phase1_swabs = ifelse(d %within% phase1_interval, phase1_swabs, 0)) %>%
  left_join(phase2_treated) %>% 
  mutate(number_of_tests = replace_na(number_of_tests, 0)) %>%
  rename(phase2_swabs = number_of_tests) %>%
  mutate(phase2_swabs = ifelse(d %within% phase2_interval, phase2_swabs, 0))




```






```{r}

check = arrest %>%
  group_by(fips_county_code, phase1_swabs) %>%
  mutate(phase1_dui = sum(dui_tot_arrests)) %>%
  mutate(phase1_dui_white = sum(dui_tot_white)) %>%
  ungroup() %>%
  group_by(fips_county_code, phase2_swabs) %>%
  mutate(phase2_dui = sum(dui_tot_arrests)) %>%
  mutate(phase2_dui_white = sum(dui_tot_white)) %>%
  ungroup() 

check = check %>%
  mutate(phase1 = ifelse(phase1_swabs == 0 ,0, 1)) %>%
  mutate(phase2 = ifelse(phase2_swabs == 0, 0, 1)) %>%
  group_by(fips_county_code) %>%
  mutate(sum1 = sum(phase1, na.rm = TRUE)) %>%
  mutate(sum2 = sum(phase2, na.rm = TRUE)) %>%
  mutate(phase12 = ifelse(sum1 != 0 & sum2 !=0, 1, 0)) %>%
  mutate(control = ifelse(sum2 == 0, 1, 0)) %>%
  ungroup()

check2 = check %>%
  mutate(Group = ifelse(control == 1, "Control", 0)) %>%
  mutate(Group = ifelse(sum2 != 0, "Phase 2 Only", Group)) %>%
  mutate(Group = ifelse(sum1 != 0, "Phase 1 and 2", Group))


```

# Average Number Of DUI Arrests, By Treatment Group

```{r}

check3 = check2 %>%
  group_by(Group, d) %>%
  summarise(average_dui_arrests = mean(dui_tot_arrests))

a = check3 %>%
  ggplot(aes(x = d, y = average_dui_arrests)) +
  geom_line(aes(color = Group)) +
  geom_smooth(aes(color = Group), se = FALSE) +
  theme_bw() +
  ylab("Average Number of DUI Arrests") +
  xlab("Date") 

ggplotly(a)

```

Interesting dip in 2020. Pandemic maybe?


# Average Number Of DUI Arrests, By Treatment Group, By Month

```{r, fig.width=11}

check3 = check2 %>%
  group_by(Group, d) %>%
  summarise(average_dui_arrests = mean(dui_tot_arrests)) %>%
  mutate(Month = format(d, "%m"))

b = check3 %>%
  ggplot(aes(x = d, y = average_dui_arrests)) +
  geom_line(aes(color = Group))  +
  theme_bw() +
  ylab("Average Number of DUI Arrests") +
  xlab("Date") +
  facet_wrap(~Month) +
  theme(strip.background =element_rect(fill="black")) +
  theme(strip.text = element_text(colour = 'white'))

ggplotly(b)

```



